### ISSUE TITLE
Support displaying version number in LogInView

### ISSUE THREAD

**Issue by 3lvis** [finn-no/FinniversKit#104]
![c7087d30-22bc-11e8-97d8-77fa3bf5dcd4](https://user-images.githubusercontent.com/1088217/37150498-349c8674-22d2-11e8-9cb0-8819bf5ceb7f.png)

**Comment by robinsalehjan** [comment]
Hi!

I can make a PR, but I have a question. The `LoginView` in master has a newer design, compared to the example above.

The attachments below is what I think looks the "cleanest", but open for suggestions :)
![iPhone X](https://user-images.githubusercontent.com/8507719/40771228-16b70616-64bd-11e8-90bc-20f02711b252.png)
![iPhone 8 Plus](https://user-images.githubusercontent.com/8507719/40771268-303a700a-64bd-11e8-9d21-e3e9771c2d60.png)
![iPad Pro 9 7-inch](https://user-images.githubusercontent.com/8507719/40771297-469bf09e-64bd-11e8-8683-24361ca4ae0d.png)
![iPad Pro 12 9-inch 2nd generation](https://user-images.githubusercontent.com/8507719/40771334-5f90181e-64bd-11e8-9f68-90c85423e494.png)

**Comment by 3lvis** [comment]
I don't think this issue is valid anymore.
