### ISSUE TITLE
iPad Support for Login & Register Views

### ISSUE THREAD

**Issue by ag12** [finn-no/FinniversKit#129]
Currently, we are showing these view modally on iPad. 
This will limit the width of the Textfield and button to the constraints set on the view. 

Soon we will have to have these view `full screen` and that won't look good. 
And of course, later we are probably going to use the new SPID SDK. 
But meanwhile, we should update the constraints on these views. (Max Width)

**_Now:_**
![simulator screen shot - ipad air - 2018-04-16 at 16 17 02](https://user-images.githubusercontent.com/1401033/38814361-a21a7796-4191-11e8-9fb7-f091e982ee13.png)

**Comment by ingridvf** [comment]
Set max width to 343px, so it has the same width as iPhone 8 with margins.

**Comment by axldyb** [comment]
Shouldn't this be a responsibility of the one using this view? Like the view controller perhaps? The constraints set on the `LoginView` can be used to set a max width or margins.

**Comment by ag12** [comment]
That's a good point 👍

**Comment by 3lvis** [comment]
I agree with Aksel, the parent should set the sizing.
