### ISSUE TITLE
Multiline not done

### ISSUE THREAD

**Issue by ingridvf** [finn-no/FinniversKit#169]
Multiline is not working as multiline at the moment since it does not span over several lines. But it should.

**Comment by axldyb** [comment]
The iOS built in `UITextField` (which we have based our textfield on) doesn't support multiline. My guess is that this is the reason it is not implemented at the moment. To fix this we would have to do something custom. Maybe modify a `UITextView` to behave as the `UITextField`.

**Comment by ingridvf** [comment]
Okey, then we can wait to fix this until someone needs a multiline I guess?

**Comment by ag12** [comment]
That `someone` could be you 🙈 
Earning your `Black Belt` 💻 🖱 
Go for it 🎖

**Comment by ingridvf** [comment]
Seems very complicated for a non-developer to fix this 🤪

**Comment by ag12** [comment]
https://gph.is/2fBrPMS

**Comment by 3lvis** [comment]
We're tracking this on Trello. Closing.
